server:
  port: 3333

spring:
  mvc:
    view:
      prefix: /template/
      suffix: .html

  datasource:
    url: jdbc:mysql://cd-cdb-cd51wfie.sql.tencentcdb.com:22111/guestbook?characterEncoding=utf8mb4&useSSL=false&serverTimezone=Asia/Shanghai&sessionVariables=character_set_client=utf8mb4,character_set_connection=utf8mb4,character_set_results=utf8mb4
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    guestbook
    username: root
    password: OuJiaXin031017

mybatis:
  config-location: classpath:mybatis/mybatis-application.xml
  mapper-locations: classpath:mybatis/mappers/*.xml
  type-aliases-package: com.example.guestbook.domain

